### ISSUE TITLE
Howdy open camera slow

### ISSUE THREAD

**Issue by hmanhng** [fufexan/dotfiles#23]
I use howdy and found it quite slow to launch the camera, I don't use linux-enable-ir-emitter
my config
```nix
    howdy = {
      enable = true;
      package = inputs.nixpkgs-howdy.legacyPackages.${pkgs.system}.howdy;
      settings = {
        core.no_confirmation = true;
        video = {
          device_path = "/dev/video0";
          force_mjpeg = true;
        };
        debug.end_report = true;
      };
    };
```
```
Time spent
  Starting up: 413ms
  Open cam + load libs: 1347ms
    Opening the camera: 1347ms
    Importing recognition libs: 959ms
  Searching for known face: 408ms
  Total time: 2168ms

Resolution
  Native: 480x-1
  Used: 320x427

Frames searched: 1 (2.45 fps)
Black frames ignored: 0 
Dark frames ignored: 0 
Certainty of winning frame: 2.531
Winning model: 0 ("Model #0")
```
Is there any way to fix it?

**Comment by fufexan** [comment]
Is `/dev/video0` your infrared camera? Is your IR blaster blinking?

**Comment by hmanhng** [comment]
My laptop camera doesn't have infrared so I don't have the linux-enable-ir-emitter service enabled
 There is only a small light that shines when the camera is activated.
 so i know it's slow every time it works.

**Comment by fufexan** [comment]
The problem might be that the full-color camera takes longer to open than an IR-camera, which is black and white. As far as I know, Howdy isn't targeting normal cameras, so you may have to put up with it being slow.

Maybe changing the recorder to "ffmpeg" instead of "opencv" is faster, but you should open an issue about this in the [Howdy repo](https://github.com/boltgolt/howdy).

**Comment by hmanhng** [comment]
I will check again, thank you for your help
